.TH GRUB-PASSWORD 1 "May 2025" "BredOS Tools" "User Commands"
.SH NAME
grub-password \- manage GRUB password protection
.SH SYNOPSIS
.B grub-password
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B grub-password
is a tool that enables or disables password protection for the GRUB bootloader.
It helps secure the system by preventing unauthorized users from modifying boot
parameters or accessing recovery options.
.SH OPTIONS
.TP
.BR \-d ", " \-\-disable
Disable GRUB password protection by removing the configuration file and regenerating GRUB configuration.
.TP
Without options, the tool will prompt for a new GRUB password and enable protection.
.SH EXAMPLES
.PP
To enable GRUB password protection (interactive):
.PP
.B grub-password
.PP
To disable GRUB password protection:
.PP
.B grub-password \-\-disable
.SH FILES
.TP
.I /etc/grub.d/99-bredos-grub-password
Configuration file created to implement password protection
.SH SEE ALSO
.BR grub-mkconfig (8),
.BR grub-mkpasswd-pbkdf2 (1)
.SH BUGS
Report bugs to the BredOS tools issue tracker at https://github.com/BredOS/bredos-tools/issues
.SH AUTHOR
Bill88t <bill88t@feline.gr>
